In [39]:

import numpy as np

from math import *

In [40]:
T = np.array([[0,1/10,-1/5,0],[1/11,0,1/11,-3/11],[-1/5,1/10,0,1/10],[0,-3/8,1/8,0]])
c = np.array([3/5,25/11,-11/10,15/8])
x = np.array([0,0,0,0]) #vector de valores iniciales
erroraceptado=0.01

In [41]:
error=1
while error>0.01:
    resultado=np.dot(T,x) + c
    print(resultado)
    print("                                                error",error)
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    x=resultado

[ 0.6         2.27272727 -1.1         1.875     ]
                                                error 1
[ 1.04727273  1.71590909 -0.80522727  0.88522727]
                                                error 1.0
[ 0.93263636  2.05330579 -1.04934091  1.13088068]
                                                error 0.57682119205298
[ 1.01519876  1.95369576 -0.96810863  0.97384272]
                                                error 0.16431877641376524
[ 0.9889913   2.01141473 -1.0102859   1.02135051]
                                                error 0.08037994847125665
[ 1.00319865  1.99224126 -0.99452174  0.99443374]
                                                error 0.02869570385848171
[ 0.99812847  2.00230688 -1.00197223  1.00359431]
                                                error 0.013510798495147403


In [56]:
def jacobiano(x):
    J = np.array(
        [[3, x[2] * sin(x[1] * x[2]), x[1] * sin(x[1] * x[2])], [2 * x[0], -162 * (x[1] + 0.1), cos(x[2])],
         [-x[1] * exp(-x[0] * x[1]), -x[0] * exp(-x[0] * x[1]), 20]])
    JInversa = np.linalg.inv(J)
    return JInversa


def Fx(x):
    x1 = 3 * x[0] - cos(x[1] * x[2]) - 1 / 2
    x2 = x[0] ** 2 - 81 * (x[1] + 0.1) ** 2 + sin(x[2]) + 1.06
    x3 = exp(-x[0] * x[1]) + 20 * x[2] + (10 * pi - 3) / 3
    xk = np.array([x1, x2, x3])
    return xk

In [60]:
x = np.array([0.1, 0.1, -0.1])  # vector de valores iniciales
error = 1
c = 0
while error > 0.01 and c < 10:
    c += 1
    r = jacobiano(x)
    feval = Fx(x)
    resultado = x - np.dot(r, feval)
    numerador = np.amax(abs((resultado - x)))
    denominador = np.amax(abs(resultado))
    error = numerador / denominador
    x = resultado

    print("Iteración:", c, " Resultado", resultado,"        error",error)


Iteración: 1  Resultado [ 0.49986967  0.01946685 -0.52152047]         error 0.8082529730255646
Iteración: 2  Resultado [ 0.50001424  0.00158859 -0.52355696]         error 0.03414768283982401
Iteración: 3  Resultado [ 5.00000113e-01  1.24447833e-05 -5.23598450e-01]         error 0.003010220115725937
